name: .NET Core

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="App-$tag-win-x64"
          dotnet publish --no-restore -c Release -o "$release_name"
    - name: Test
      run: dotnet test --no-restore --verbosity normal
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Build
        shell: bash
        run: |
          tag="testtest"
          release_name="Calling-$tag"

          # Build everything
          dotnet publish --framework netcoreapp3.1 --runtime "win-x64 -c Release -o "$release_name"

          7z a -tzip "${release_name}.zip" "./${release_name}/*"

          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Calling*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
